### ISSUE TITLE
function need: 希望添加进程禁用和快捷键更改

### ISSUE THREAD

**Issue by Akashiya-Chime** [majorworld/MousePlus#1]
- 进程禁用：因为软件在全局下作用，当我处于某些进程时，不希望该软件运行（例如它会和我浏览器的鼠标右键手势冲突，所以不希望在浏览器下运行）
- 快捷键更改：希望可以自定功能执行按键（例如鼠标中键或者侧键）

**Comment by majorworld** [comment]
好的，下个版本添加进程排除名单。

触发快捷键修改我尝试一下，因为那样感觉操作会有点不统一，比如中键调用轮盘后，是要点击轮盘来选择动作了，不同于滑动了。帮助说明文字都要修改。
