### ISSUE TITLE
锁屏快捷键（Win + L）无法使用

### ISSUE THREAD

**Issue by CharlesXSong** [majorworld/MousePlus#11]
中键选择方框→输入或选择组合键，LWin,L，无法锁屏，从现象分析，只是按下了“L”键。
![Snipaste_2021-05-31_10-53-21](https://user-images.githubusercontent.com/50441285/120133284-6f69f100-c1fe-11eb-9996-107dc3411874.png)
![image](https://user-images.githubusercontent.com/50441285/120133370-aa6c2480-c1fe-11eb-9725-85a21a4cc833.png)

**Comment by majorworld** [comment]
你好，微软貌似屏蔽了模拟锁屏的快捷键，其他的都是可以的。
所以【5、输入或选择命令】提供了锁屏命令，欢迎体验。

**Comment by CharlesXSong** [comment]
> 你好，微软貌似屏蔽了模拟锁屏的快捷键，其他的都是可以的。
> 所以【5、输入或选择命令】提供了锁屏命令，欢迎体验。

非常感谢！自己没有仔细看，这个可以用！
