### ISSUE TITLE
LWin,L怎么锁不了屏？

### ISSUE THREAD

**Issue by victorwwd** [majorworld/MousePlus#6]
要实现锁屏功能，采用组合键LWin,L或RWin,L，都没有效果？LWin或RWin不是windows键吗？sleep用起来也没效果
![image](https://user-images.githubusercontent.com/17702941/119433315-9761dc00-bd48-11eb-8233-747cf42e68f6.png)

**Comment by majorworld** [comment]
你好，我试了一下，LWin+L这套组合键确实不行，可能是被微软屏蔽了这种模拟按键，其他的快捷键组合都可以，建议换成“5、输入或选择命令的模式”

rundll32.exe user32.dll LockWorkStation

填入该命令即可锁屏，非常感谢你的反馈。

**Comment by majorworld** [comment]
LWin或RWin确实是windows键，如果使用LWin,Tab显示任务视图都是可以的。

Sleep是睡眠按钮，可能部分电脑不支持。

**Comment by majorworld** [comment]
LWin或RWin确实是windows键，如果使用LWin,Tab显示任务视图都是可以的。

Sleep是睡眠按钮，可能部分电脑不支持。

**Comment by victorwwd** [comment]
> 你好，我试了一下，LWin+L这套组合键确实不行，可能是被微软屏蔽了这种模拟按键，其他的快捷键组合都可以，建议换成“5、输入或选择命令的模式”
> 
> rundll32.exe user32.dll LockWorkStation
> 
> 填入该命令即可锁屏，非常感谢你的反馈。

已用该命令实现锁屏，tks
