### ISSUE TITLE
为啥不放到 github release 里呢? 

### ISSUE THREAD

**Issue by b19g3r** [majorworld/MousePlus#9]
为啥不放到 github release 里呢?

**Comment by majorworld** [comment]
我这边访问GitHub非常不稳定，上传和下载非常困难，这里仅做信息公布。

本来想放在Gitee上的，包括Release后的文件，但是放个链接竟然直接给封了，啊哈哈嗝。

**Comment by majorworld** [comment]
对了，还有一个原因是，我想后台里瞅瞅下载量（有点成就感），release看不到的。
